services:
  # Spring Boot API Service
  - type: web
    name: foodies-api
    env: java
    plan: free
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/foodiesapi-0.0.1-SNAPSHOT.jar"
    healthCheckPath: /actuator/health
    
    # Add health check endpoint
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        value: 1361ae1fcc3a6babe6a9ed6d570fe7891753d678bfd2a07f9abc173f747d83654425838f4951f746a6288995eac275b3452aa336b99ae3f5749f4c43a50f0591
      - key: CLOUDFLARE_ACCESS_KEY
        sync: false
      - key: CLOUDFLARE_SECRET_KEY
        sync: false
      - key: CLOUDFLARE_R2_ENDPOINT
        sync: false
      - key: CLOUDFLARE_BUCKET_NAME
        sync: false
