spring.application.name=foodiesapi

#postgresql configuration for production
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/foodies}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#cloudflare r2 configuration
cloudflare.access.key=${CLOUDFLARE_ACCESS_KEY:default_access_key}
cloudflare.secret.key=${CLOUDFLARE_SECRET_KEY:default_secret_key}
cloudflare.endpoint=${CLOUDFLARE_R2_ENDPOINT:https://default.r2.cloudflarestorage.com}
cloudflare.bucketname=${CLOUDFLARE_BUCKET_NAME:default_bucket}

jwt.secret.key=${JWT_SECRET:1361ae1fcc3a6babe6a9ed6d570fe7891753d678bfd2a07f9abc173f747d83654425838f4951f746a6288995eac275b3452aa336b99ae3f5749f4c43a50f0591}

#actuator configuration for health check
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always